export const FETCH_MOVIE_DETAILS_REQUEST = "FETCH_MOVIE_DETAILS_REQUEST";
export const FETCH_MOVIE_DETAILS_SUCCESS = "FETCH_MOVIE_DETAILS_SUCCESS";
export const FETCH_MOVIE_DETAILS_FAILURE = "FETCH_MOVIE_DETAILS_FAILURE";
